### ISSUE TITLE
ThreadsOnFork worker never seems to actually connect on Windows

### ISSUE THREAD

**Issue by contentfree** [nesquena/backburner#105]
Yes I know: Windows… However, it's a requirement for me for a particular job task. 

Running the backburner CLI seems to start the process correctly, but no connection to beanstalkd is made (and no work is done). Killing the process does not print out the expected `[ThreadsOnFork workers] Stopping forks:`

Anyone know of a fix?

**Comment by nesquena** [comment]
ThreadsOnFork was never implemented to work on Windows unfortunately if I recall correctly it only works on unix-based systems. We should probably do a better job of documenting this and/or exploring if there's a fix.
