### ISSUE TITLE
Releasing 1.1

### ISSUE THREAD

**Issue by nesquena** [nesquena/backburner#109]
@contentfree Hi Dave, I added you to [readme here](https://github.com/nesquena/backburner/blob/master/README.md#acknowledgements) and added you as a collaborator of this repo although I am still happy to review pull requests and discuss them. Unfortunately, while I still love and use this project, I don't have as much time as I use to develop on it. Would you be interested in being a co-maintainer?

First step would be if you could help [compile the changelog](https://github.com/nesquena/backburner/blob/master/CHANGELOG.md) so we can do a 1.1 release. Thanks for all you've done so far to further this project with needed features and improving the docs, I appreciate it.

**Comment by contentfree** [comment]
OK, cool.

**Comment by contentfree** [comment]
Updated the changelog in prep for 1.1. What's your process for releasing? Make a new tag, `gem build` and `gem push`?

**Comment by nesquena** [comment]
Here's the workflow

1. Update `CHANGELOG.md` with changes
2. Update `lib/backburner/version.rb` version number
3. Check to ensure tests pass
4. Run `rake release` from root directory

**Comment by nesquena** [comment]
I just ran that and released here: https://rubygems.org/gems/backburner ! Thanks!

**Comment by nesquena** [comment]
Do you have a rubygems account, what's the associated email, so I can add you as an owner?

**Comment by contentfree** [comment]
davemyron​

**Comment by nesquena** [comment]
I think I need your email associated with that account
