### ISSUE TITLE
Is there a timetable for releasing version 1.3.1?

### ISSUE THREAD

**Issue by harukizaemon** [nesquena/backburner#130]
I notice the change log says April but the official gem is still 1.3.0.

**Comment by nesquena** [comment]
@harukizaemon pushed just now <https://rubygems.org/gems/backburner>. Thanks for the reminder

**Comment by eltone** [comment]
@nesquena could you possibly push another release out? I'd like to use my serialization changes via rubygems.

**Comment by nesquena** [comment]
@eltone sorry for the delay here. I've released [1.4.0](https://rubygems.org/gems/backburner/versions/1.4.0) and added you @eltone as a contributor. I can add you to the rubygems owner as well if you'd like to help maintain this gem. Thanks!

**Comment by eltone** [comment]
@nesquena thanks, I'd be happy to help out! My username is the same on rubygems.

**Comment by nesquena** [comment]
@eltone Great! I've added you to rubygems owner
