### ISSUE TITLE
Rake task for restarting

### ISSUE THREAD

**Issue by activestylus** [nesquena/backburner#134]
`rake backburner:work` is great for getting up and running

But what if I need to reboot the process?

Sidekiq, DelayedJob and the rest all have a rake task for `stop` and `restart`

Shouldn't these be baked into backburner as well?

**Comment by nesquena** [comment]
Right now we recommend using something like monit or god https://github.com/nesquena/backburner/blob/master/README.md#workers-in-production but you can also use https://github.com/nesquena/backburner/blob/master/README.md#command-line-interface to start and stop at will
