### ISSUE TITLE
Incompatible with foreman?

### ISSUE THREAD

**Issue by haffla** [nesquena/backburner#148]
Running `bundle exec backburner` works as expected. The output is

```
Starting backburner service...
Working 1 queues: [ backburner.worker.queue.backburner-jobs ]
```

When I put the same command into a `Procfile` and run `foreman start` it only says

```
22:01:41 backburner.1 | started with pid 7764
```

When I hit CTRL-C to abort I get

```
^C22:02:03 system       | SIGINT received, starting shutdown
22:02:03 backburner.1 | Starting backburner service...
22:02:03 backburner.1 | Working 1 queues: [ backburner.worker.queue.backburner-jobs ]
22:02:04 system       | sending SIGTERM to all processes
22:02:04 backburner.1 | exited with code 0
```

So it seems that the process only starts when I kill foreman. Any idea what could be the problem?

**Comment by eltone** [comment]
I'm not that familiar with foreman but there may be some stdout buffering happening here. Are jobs being reserved at all?

**Comment by haffla** [comment]
No jobs are not reserved. Maybe I forgot to add that this is in a Vagrant box?
