### ISSUE TITLE
concurrent-ruby restrictive dependency

### ISSUE THREAD

**Issue by pitr-ch** [nesquena/backburner#160]
Hi @nesquena,
would you consider changing https://github.com/nesquena/backburner/blob/master/backburner.gemspec#L21 to `'~> 1.0', '>= 1.0.1'`? It would allow users of backburner to get new 1.1.0 version when released. There is currently pre1 of 1.1.0. Thanks

**Comment by nesquena** [comment]
How's that? https://github.com/nesquena/backburner/commit/2f87e291cb8ef2e23587ce552c5a194324afc34e

**Comment by pitr-ch** [comment]
Awesome 👍 Thanks!
