### ISSUE TITLE
ActiveJob based of backburner is restarting the job within

### ISSUE THREAD

**Issue by praveenkumarsinha** [nesquena/backburner#167]
Sorry if this is stupid but i have a situation.
ActiveJob based of backburner is restarting the job within, without any proper explanation.
While the code executes successfully when executed in non-async mode.

Any thoughts?

**Comment by contentfree** [comment]
What version of ActiveJob? Are you using a retry handler?

**Comment by praveenkumarsinha** [comment]
O i think i got the answer. It's the timeout. But unfortunately it never pops up in any kind of log when "god" keeps a check on its process status.

When i disable god and process halts then i see a log output like this 
`Exception Backburner::Job::JobTimeout -> ActiveJob::QueueAdapters::BackburnerAdapter::JobWrapper({"job_class"=>"ImporterJob", "job_id"=>"e24002fe-0fbb-47c0-9f1b-1ec7f072f552", "provider_job_id"=>nil, "queue_name"=>"development.default", "priority"=>nil, "arguments"=>["dry_run", "sample_import.csv"], "executions"=>0, "exception_executions"=>{}, "locale"=>"en", "timezone"=>"UTC", "enqueued_at"=>"2020-11-24T11:32:56Z"}) hit 119s timeout.`
