### ISSUE TITLE
Upgrading Beaneater to 1.1 makes job queues fail

### ISSUE THREAD

**Issue by colmexdev** [nesquena/backburner#170]
Hello there!

   I recently updated gems in one of my projects and realized that Beaneater just went from 1.0.0 to 1.1.0; after this update, every enqueued job displayed the following message in logs:
`[ActiveJob] Failed enqueuing <job> to Backburner(<queue>): ArgumentError (wrong number of arguments (given 2, expected 1))`

   Is there a way to solve this? Or should I stick to the 1.0.0 version of Beaneater by now? I don't seem to find anything else that can enlighten more.

   I'm using Ruby 3.0.0 and Rails 6.1.3.1 and Beanstalkd 1.11.

   Thank you so much in advance!

**Comment by nesquena** [comment]
Yes, go ahead and lock to 1.0 for now, should sort out the problem short term.

**Comment by nesquena** [comment]
@colmexdev I believe this is fixed now in the 1.1.1 release, can you confirm? I also hooked up beaneater to be tested against Ruby 3.

**Comment by colmexdev** [comment]
Hey @nesquena !

   It seems that there are no other issues with the new beaneater version (1.1.1), so I'll close this.

   Thank you very much for your response and effort.
