### ISSUE TITLE
Replacing File.exists? with File.exist? as the former has been removed from ruby 2.7.7

### ISSUE THREAD

**Issue by ShrutiSaagar** [nesquena/backburner#177]
Can we have the change made in load_environment function in cli.rb so that it can support latest ruby versions?
I can raise the PR as well if possible.

**Comment by nesquena** [comment]
Yes I'd be happy to merge that change

**Comment by ShrutiSaagar** [comment]
Hey can you add me as a contributor to the repo so that I'll create the PR?

**Comment by nesquena** [comment]
Added

**Comment by ShrutiSaagar** [comment]
Thank you for the quick response @nesquena , raised the PR https://github.com/nesquena/backburner/pull/178 .

**Comment by ShrutiSaagar** [comment]
Can we create a new release 1.6.1 for the change so that it can go whenever someone updates their gemfile?
Should I update changelog and version.rb with 1.6.1?

**Comment by ShrutiSaagar** [comment]
Done in https://github.com/nesquena/backburner/pull/179 . 👍
