### ISSUE TITLE
NewRelic monitoring hooks

### ISSUE THREAD

**Issue by nesquena** [nesquena/backburner#34]
Track backburner tasks with newrelic API for background processing.

**Comment by contentfree** [comment]
So I finally got this one added to my app. 

What I did was follow NewRelic's instructions on adding the gem and configuring the agent with the YAML file. Then, in an initializer, I did the following:

```ruby
if defined?(::NewRelic)
  Backburner::Job.include ::NewRelic::Agent::Instrumentation::ControllerInstrumentation
  Backburner::Job.add_transaction_tracer :process, category: :task
end
```

And now I've got transaction tracing for jobs. 

IMO, we can close this if the above is satisfactory @nesquena

**Comment by nesquena** [comment]
Oh wow that is easy, thanks for posting. Might be cool for us to add this to the README or Wiki. Nice to see its so easy.

**Comment by nesquena** [comment]
Added here: https://github.com/nesquena/backburner/wiki/Setup#new-relic-agent
