### ISSUE TITLE
Problems with environment when running backburner as daemon

### ISSUE THREAD

**Issue by gitgary** [nesquena/backburner#43]
When I run backburner as a daemon, it seems to _always_ prefix the queue with 'backburner.worker' irrespective of what is in my apps config file or what I provide as command-line parameters.

Working 1 queues: [ backburner.worker.queue.myapp.mailer ]

I tried to change the app config to load work into the queue named above, but then it seems that the environment isn't loaded properly so jobs that get queued get immediately buried.

The rake task always works but is ugly and difficult to connect to monit or God. This is what I'm doing as a short-term work around.
nohup rake backburner:work &

Any ideas?

  config.beanstalk_url    = ["beanstalk://127.0.0.1:11300"]
  config.tube_namespace   = "myapp"
  config.on_error         = lambda { |e| puts e }
  config.max_job_retries  = 3 # default 0 retries
  config.retry_delay      = 5 # default 5 seconds
  config.default_priority = 65536
  config.respond_timeout  = 120
  config.default_worker   = Backburner::Workers::Simple
  config.default_queues   = ["staging", "staging-mailer"]
  config.logger           = Logger.new("backburner-staging.log")

**Comment by Nick-DeSimone** [comment]
I know this is closed, but I'm having the same problem in 1.3

**Comment by Nick-DeSimone** [comment]
I found a way around this using dotenv-rails.
