### ISSUE TITLE
Checking on a job after it's been put into the queue?

### ISSUE THREAD

**Issue by nathanpalmer** [nesquena/backburner#50]
Is there a way for me to check on a job after it's been enqueued? Preferably after calling "async.command" I could get an id back that I can go back and check so I can follow up afterwards?

My use-case is this. I am triggering async jobs from several parts of my web application. I'd like to give the user feedback about the completion of those jobs and I can't move the user forward until they finish. There are other parts where we trigger a job but I need to give them a way to see if they were successful or failed. I'm trying to find a way where I don't need to wrap all of these with another layer of database tables to provide this information.

**Comment by geoffroymontel** [comment]
Hello

I have the same FR. I'd also like to show the users the position in the queue of a job (because the worker can only take one at the time and it's pretty slow).

Best

Geoffroy

**Comment by lewstherin** [comment]
Isn't this done? After a successful enqueue, the response returned has the id and the status. Just checked with 1.3.1
@nesquena This issue can be closed.
