### ISSUE TITLE
Backburner jobs get stuck in 'ready' state.

### ISSUE THREAD

**Issue by marcusramberg** [nesquena/backburner#60]
I have some trouble with backburner. I have a setup with two workers running against two beanstalk instances. Somehow, it seems like jobs get 'stuck' somehow sometimes.  I can see the workers in beanstalkd view like this:

![beanstalkd_view_-_1_2_7](https://cloud.githubusercontent.com/assets/5526/3017945/07201cfe-df80-11e3-9036-6987d0b951c3.png)

And if I keep restarting the workers, it eventually picks up the jobs and process them. I'm wondering if this could be related to having multiple beanstalk servers, but I am a bit at a loss about how to debug further.

**Comment by jshow** [comment]
@marcusramberg , I looked for your fork, couldn't find it - was it merged ? thanks
