### ISSUE TITLE
How can clear enqueue jobs in backburner with beanstalkd in rails

### ISSUE THREAD

**Issue by mzaragoza** [nesquena/backburner#81]
How can I remove all jobs from a campaign?

**Comment by ryanjohns** [comment]
I would either use the beaneater API directly or use a tool like beanstalkd_view gem which provides a web-based management UI.

```ruby
beanstalk = Beaneater::Pool.new(['localhost:11300'])
tube = beanstalk.tubes["some-tube"]
while tube.peek(:ready)
  job = tube.reserve
  job.delete
end
beanstalk.close
```

https://github.com/denniskuczynski/beanstalkd_view
