### ISSUE TITLE
Readme error about worker start

### ISSUE THREAD

**Issue by Aethelflaed** [nesquena/backburner#83]
The readme states:

>This will process jobs in all queues but you can also restrict processing to specific queues:
>```ruby
>Backburner.work('newsletter-sender,push-notifier')
>```

But you actually have to pass several parameters or an array for this to work, e.g. :

```ruby
Backburner.word('newsletter-sender', 'push-notifier')
# Or
Backburner.word(%w(newsletter-sender push-notifier))
```

**Comment by nesquena** [comment]
0004ae86a784dec1a8901dcf1568e961393b7b8c Thanks
