### ISSUE TITLE
Multiple beanstalkd servers issue

### ISSUE THREAD

**Issue by coffeebite** [nesquena/backburner#85]
Hey guys ... sorry if this sounds like a super noob question.

So I am using backburner + beanstalkd. 

Beanstalk settings:
- 3 servers
- persistence on

Worker settings:
- 2 different servers
- 50 workers per server (ie. 50 different "rake backburner:work" processes, managed by god).
- Simple workers
- 8 CPUs per worker box

We consistently see a few thousand jobs in "ready" state (using beanstalkd_view) and that number does not come down no matter what I do. I have tried the following

- increasing the # of beanstalk servers
- increasing the # of workers per server. In fact, I decreased it to one server with 25 workers and the rate of completion of the jobs was the same.

The number of reserved jobs is always 1 or 0 no matter how many workers we have. Also, often, it shows all my workers are in "waiting" state.

Am I misunderstanding how backburner is supposed to work? Can I only have one worker per tube or something?

UPDATE

If I use just one beanstalkd server, things are fine.

**Comment by contentfree** [comment]
@coffeebite Since Beaneater (and therefore Backburner) no longer supports a server pool, I'm going to close this issue.

**Comment by nesquena** [comment]
Yep, pool was always half-baked anyways, makes sense.

**Comment by coffeebite** [comment]
Sorry to reopen this, but can we update the docs to reflect this? I still see this which makes me feel that I can use multiple queue servers:

![screen shot 2016-11-30 at 18 40 03](https://cloud.githubusercontent.com/assets/763616/20779901/7aa37d0c-b72c-11e6-885f-5b440ec07618.png)

**Comment by nesquena** [comment]
@coffeebite I think I have adjusted the readme now accordingly, thanks.
